let members=[],memberSchemes=[];
const memberEsc=v=>escHtml(v);
async function loadMembers(){try{const d=await fintrackApi("/members");members=d.members||[];const s=await fintrackApi("/schemes");memberSchemes=s.schemes||[];renderMembers();fillSchemeOptions();}catch(e){alert(e.message)}}
function renderMembers(){const body=membersTableBody;if(!body)return;const q=(memberSearch?.value||"").toLowerCase(),st=statusFilter?.value||"all";const rows=members.filter(m=>(st==="all"||m.status===st)&&(!q||[m.name,m.email,m.phone].join(" ").toLowerCase().includes(q)));memberCount.textContent=rows.length;body.innerHTML=rows.map(m=>`<tr><td><b>${memberEsc(m.name)}</b><small>${memberEsc(m.email)}</small></td><td>${memberEsc(m.phone)}</td><td>${memberEsc(m.status)}</td><td>${memberEsc(new Date(m.joinedDate).toLocaleDateString("en-IN"))}</td><td><button class="btn btn-small" onclick="openMemberLedger('${m.id}')">Ledger</button> <button class="btn btn-small" onclick="editMember('${m.id}')">Edit</button> <button class="btn btn-small" ${m.hasLogin?"disabled":""} onclick="createMemberAccount('${m.id}')">${m.hasLogin?"Account Created":"Create Account for Member"}</button> <button class="btn btn-small danger" onclick="deleteMember('${m.id}')">Delete</button></td></tr>`).join("")||`<tr><td colspan="5">No members found.</td></tr>`;}
function fillSchemeOptions(){if(!memberScheme)return;memberScheme.innerHTML='<option value="">No Scheme - Add to Directory Only</option>'+memberSchemes.map(s=>`<option value="${s.id}">${memberEsc(s.name)} (${memberEsc(s.type)})</option>`).join("");}
function addLoginFields(){}
function removeLoginFields(){document.getElementById("memberLoginFields")?.remove();}
function toggleMemberOption(){const isNew=memberOption.value==="new";existingMemberGroup.style.display=isNew?"none":"";memberName.disabled=!isNew;memberEmail.disabled=!isNew;memberPhone.disabled=!isNew;addLoginFields();}
function onSelectExistingMember(){const m=members.find(x=>String(x.id)===String(existingMemberSelect.value));if(!m)return;memberName.value=m.name;memberEmail.value=m.email;memberPhone.value=m.phone;memberJoinedDate.value=String(m.joinedDate).slice(0,10);memberStatus.value=m.status;memberName.disabled=memberEmail.disabled=memberPhone.disabled=true;}
function openCreateMemberModal(){memberForm.reset();memberId.value="";memberOption.value="new";existingMemberGroup.style.display="none";memberName.disabled=memberEmail.disabled=memberPhone.disabled=false;memberJoinedDate.value=new Date().toISOString().slice(0,10);memberModal.classList.add("active");}
function closeMemberModal(){memberModal?.classList.remove("active");}
function editMember(id){const m=members.find(x=>String(x.id)===String(id));if(!m)return;openCreateMemberModal();memberId.value=m.id;memberName.value=m.name;memberEmail.value=m.email;memberPhone.value=m.phone;memberJoinedDate.value=String(m.joinedDate).slice(0,10);memberStatus.value=m.status;memberOption.value="new";removeLoginFields();}
async function saveMember(e){e.preventDefault();const id=memberId.value;const payload={name:memberName.value.trim(),email:memberEmail.value.trim(),phone:memberPhone.value.trim(),joinedDate:memberJoinedDate.value,status:memberStatus.value};if(!/^\d{10}$/.test(payload.phone))return alert("Phone must be 10 digits.");try{let member;if(id){const d=await fintrackApi("/members/"+id,{method:"PATCH",body:JSON.stringify(payload)});member=d.member;}else{const d=await fintrackApi("/members",{method:"POST",body:JSON.stringify(payload)});member=d.member;}
 if(!id&&memberScheme.value&&memberTicket.value){await fintrackApi(`/members/${member.id}/tickets`,{method:"POST",body:JSON.stringify({schemeId:memberScheme.value,ticketNumber:memberTicket.value})});}
 closeMemberModal();await loadMembers();}catch(err){alert(err.message)}}
async function createMemberAccount(id){if(!confirm("Create this member's login and email the temporary credentials to their registered email address?"))return;try{const d=await fintrackApi(`/members/${id}/account`,{method:"POST",body:"{}"});alert(d.message);await loadMembers();}catch(e){alert(e.message)}}
async function deleteMember(id){if(!confirm("Delete this member?"))return;try{await fintrackApi("/members/"+id,{method:"DELETE"});await loadMembers();}catch(e){alert(e.message)}}
async function openMemberLedger(id){const m=members.find(x=>String(x.id)===String(id));if(!m)return;const [t,p,w]=await Promise.all([fintrackApi(`/members/${id}/tickets`),fintrackApi("/payments"),fintrackApi("/winners")]);const rows=(p.payments||[]).filter(x=>String(x.member?._id||x.member)===id);const wins=(w.winners||[]).filter(x=>String(x.member?._id||x.member)===id);memberLedgerContent.innerHTML=`<h3>${memberEsc(m.name)}</h3><p>${memberEsc(m.email)} · ${memberEsc(m.phone)}</p><h4>Tickets</h4>${(t.tickets||[]).map(x=>`<p>${memberEsc(x.scheme?.name||"Scheme")} — Ticket #${memberEsc(x.ticketNumber)} ${x.winningMonth?`— Winner Month ${x.winningMonth}`:""}</p>`).join("")||"<p>No tickets.</p>"}<h4>Payments</h4>${rows.map(x=>`<p>${memberEsc(x.scheme?.name||"Scheme")} — Month ${x.month} — ${money(x.amount)} — ${x.status}</p>`).join("")||"<p>No payments.</p>"}<h4>Winners</h4>${wins.map(x=>`<p>${memberEsc(x.scheme?.name||"Scheme")} — Month ${x.month} — Ticket #${memberEsc(x.ticketNumber)}</p>`).join("")||"<p>No winners.</p>"}`;memberLedgerModal.classList.add("active");}
function closeMemberLedger(){memberLedgerModal?.classList.remove("active");}
document.addEventListener("DOMContentLoaded",()=>{loadMembers();memberSearch?.addEventListener("input",renderMembers);statusFilter?.addEventListener("change",renderMembers);});

function openAddMemberModal(){openCreateMemberModal();} function filterMembers(){renderMembers();} function toggleSchemeFields(){} function addMember(){openCreateMemberModal();}
