let payRows=[],payMembers=[],paySchemes=[],payTickets=[];
function dueDateClient(s,m){if(!s?.startDate)return"";const d=new Date(s.startDate),day=d.getUTCDate(),base=new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+Number(m)-1,1));if(day===25)return new Date(Date.UTC(base.getUTCFullYear(),base.getUTCMonth()+1,5)).toISOString().slice(0,10);const map={1:10,5:15,10:20,15:25};base.setUTCDate(map[day]||Math.min(day+10,new Date(Date.UTC(base.getUTCFullYear(),base.getUTCMonth()+1,0)).getUTCDate()));return base.toISOString().slice(0,10);}
async function loadPayments(){try{const [p,m,s]=await Promise.all([fintrackApi("/payments"),fintrackApi("/members"),fintrackApi("/schemes")]);payRows=p.payments||[];payMembers=m.members||[];paySchemes=s.schemes||[];renderPayments();fillPaymentForm();loadOnlineRequests();loadPayouts();}catch(e){alert(e.message)}}
function renderPayments(){const body=paymentTableBody;if(!body)return;const q=(paymentSearch?.value||"").toLowerCase(),sf=schemeFilter?.value||"all",st=statusFilter?.value||"all";const rows=payRows.filter(p=>(sf==="all"||String(p.scheme?._id||p.scheme)===sf)&&(st==="all"||p.status===st)&&(!q||[p.member?.name,p.scheme?.name,p.ticketNumber,p.transactionId].join(" ").toLowerCase().includes(q)));paymentCount.textContent=rows.length;const paid=payRows.filter(p=>p.status==="paid");totalPaid.textContent=money(paid.reduce((a,p)=>a+p.amount,0));totalPending.textContent=money(payRows.filter(p=>p.status==="pending").reduce((a,p)=>a+p.amount,0));totalOverdue.textContent="—";totalRecords.textContent=payRows.length;body.innerHTML=rows.map(p=>`<tr><td><b>${escHtml(p.member?.name||"—")}</b><small>${escHtml(p.member?.email||"")}</small></td><td>${escHtml(p.scheme?.name||"—")}</td><td>#${escHtml(p.ticketNumber)}</td><td>Month ${p.month}</td><td>${money(p.amount)}</td><td>${dateText(p.dueDate)}</td><td>${dateText(p.paymentDate)}</td><td><span class="status ${p.status}">${p.status}</span></td><td>${escHtml(p.transactionId||"—")}</td></tr>`).join("")||`<tr><td colspan="10">No payments found.</td></tr>`;}
function fillPaymentForm(){schemeFilter.innerHTML='<option value="all">All Schemes</option>'+paySchemes.map(s=>`<option value="${s.id}">${escHtml(s.name)}</option>`).join("");paymentScheme.innerHTML='<option value="">Select Chit Scheme</option>'+paySchemes.map(s=>`<option value="${s.id}">${escHtml(s.name)}</option>`).join("");paymentScheme.onchange=async()=>{const rows=(await fintrackApi(`/schemes/${paymentScheme.value}/tickets`)).tickets||[];paymentTicket.innerHTML='<option value="">Select Ticket</option>'+rows.map(t=>`<option value="${escHtml(t.ticketNumber)}" data-member="${t.member._id}">${escHtml(t.ticketNumber)} — ${escHtml(t.member.name)}</option>`).join("");paymentMember.innerHTML='<option value="">Select Member</option>'+rows.map(t=>`<option value="${t.member._id}">${escHtml(t.member.name)}</option>`).join("");paymentMember.disabled=false;};paymentTicket.onchange=()=>{const o=paymentTicket.selectedOptions[0];if(o)paymentMember.value=o.dataset.member||"";updatePaymentAmount();};paymentMonth.oninput=updatePaymentAmount;}
async function updatePaymentAmount(){const s=paySchemes.find(x=>String(x.id)===String(paymentScheme.value));if(!s)return;const m=Number(paymentMonth.value);paymentAmount.value=window.fintrackPaymentAmount(s,m)||0;paymentDueDate.value=dueDateClient(s,m);}
function openCreatePaymentModal(){paymentForm.reset();paymentModal.classList.add("active");}
function closePaymentModal(){paymentModal?.classList.remove("active");}
async function savePayment(e){e.preventDefault();try{await fintrackApi("/payments/manual",{method:"POST",body:JSON.stringify({memberId:paymentMember.value,schemeId:paymentScheme.value,ticketNumber:paymentTicket.value,month:Number(paymentMonth.value),method:paymentMethod.value,transactionId:transactionId.value,status:paymentStatus.value})});closePaymentModal();await loadPayments();}catch(err){alert(err.message)}}
async function loadOnlineRequests(){try{const d=await fintrackApi("/payments/online/pending");const rows=d.requests||[];onlineRequestPendingCount.textContent=rows.length;onlinePaymentRequestBody.innerHTML=rows.map(r=>`<tr><td>${escHtml(r.member?.name||"—")}</td><td>${escHtml(r.scheme?.name||"—")}</td><td>#${escHtml(r.ticketNumber)}</td><td>Month ${r.month}</td><td>${money(r.amount)}</td><td>${escHtml(r.paymentMethod)}<br>UTR: ${escHtml(r.utr)}</td><td>${dateText(r.submittedAt)}</td><td><button class="btn btn-small" onclick="reviewOnline('${r._id}')">Review</button></td></tr>`).join("")||`<tr><td colspan="9">No pending online requests.</td></tr>`;}catch(e){console.error(e)}}
async function reviewOnline(id){try{const d=await fintrackApi("/payments/online/pending"),r=(d.requests||[]).find(x=>String(x._id)===String(id));if(!r)return;const ok=confirm(`Approve payment?\n${r.member.name} — ${r.scheme.name}\nMonth ${r.month} — ${money(r.amount)}\nUTR: ${r.utr}`);if(ok)await fintrackApi("/payments/online/"+id+"/approve",{method:"POST",body:"{}"});else if(confirm("Reject this request?"))await fintrackApi("/payments/online/"+id+"/reject",{method:"POST",body:JSON.stringify({reason:"Rejected by admin"})});await loadPayments();}catch(e){alert(e.message)}}
async function loadPayouts(){try{const d=await fintrackApi("/payouts"),rows=d.payouts||[];adminPayoutCount.textContent=rows.length;adminPayoutTableBody.innerHTML=rows.map(p=>`<tr><td>${escHtml(p.member?.name||"—")}</td><td>${escHtml(p.scheme?.name||"—")}</td><td>#${escHtml(p.ticketNumber)}</td><td>Month ${p.month}</td><td>${p.type==="gold"?`${p.goldGrams} grams`:money(p.amount)}</td><td>${p.status}</td><td>${p.status==="pending"?`<button class="btn btn-small" onclick="markPayout('${p._id}')">Mark Paid</button>`:"Paid"}</td></tr>`).join("")||`<tr><td colspan="7">No payouts.</td></tr>`;}catch(e){console.error(e)}}
async function markPayout(id){try{await fintrackApi("/payouts/"+id+"/pay",{method:"PATCH",body:JSON.stringify({method:"Bank Transfer"})});loadPayouts();}catch(e){alert(e.message)}}
document.addEventListener("DOMContentLoaded",()=>{loadPayments();paymentForm?.addEventListener("submit",savePayment);paymentSearch?.addEventListener("input",renderPayments);statusFilter?.addEventListener("change",renderPayments);});

function refreshPayments(){loadPayments()} function filterPayments(){renderPayments()} function addPayment(){openCreatePaymentModal()}
