document.addEventListener("DOMContentLoaded",async()=>{const id=new URLSearchParams(location.search).get("id");if(!id)return;try{const [s,t,w,p]=await Promise.all([fintrackApi("/schemes/"+id),fintrackApi("/schemes/"+id+"/tickets"),fintrackApi("/winners"),fintrackApi("/payments")]);const x=s.scheme, tickets=t.tickets||[], winners=(w.winners||[]).filter(v=>String(v.scheme?._id||v.scheme)===String(id)), pays=(p.payments||[]).filter(v=>String(v.scheme?._id||v.scheme)===String(id));schemeName.textContent=x.name;breadcrumbName.textContent=x.name;schemeStatus.textContent=x.status;schemeSubtitle.textContent=`${x.type} chit`;totalAmount.textContent=x.type==="gold"?`${x.goldGrams||0} grams`:money(x.totalAmount);baseInstallment.textContent=money(x.baseAmount);duration.textContent=x.duration;memberCount.textContent=tickets.length;infoName.textContent=x.name;infoType.textContent=x.type;infoAmount.textContent=x.type==="gold"?`${x.goldGrams||0} grams`:money(x.totalAmount);infoInstallment.textContent=money(x.baseAmount);infoDuration.textContent=x.duration;infoStartDate.textContent=dateText(x.startDate);infoStatus.textContent=x.status;availableSlots.textContent=Math.max(0,x.capacity-tickets.length);capacityNumber.textContent=x.capacity;capacityProgress.style.width=Math.min(100,tickets.length/x.capacity*100)+"%";membersTable.innerHTML=tickets.map(q=>`<tr><td>${escHtml(q.member?.name||"—")}</td><td>#${escHtml(q.ticketNumber)}</td><td>${q.winningMonth||"—"}</td></tr>`).join("")||"<tr><td colspan=3>No members.</td></tr>";winnersTable.innerHTML=winners.map(q=>`<tr><td>${escHtml(q.member?.name||"—")}</td><td>#${escHtml(q.ticketNumber||"—")}</td><td>${q.month}</td><td>${x.type==="gold"?`${q.goldGrams} grams`:money(q.payout)}</td></tr>`).join("")||"<tr><td colspan=4>No winners.</td></tr>";paymentsTable.innerHTML=pays.map(q=>`<tr><td>${escHtml(q.member?.name||"—")}</td><td>#${escHtml(q.ticketNumber)}</td><td>${q.month}</td><td>${money(q.amount)}</td><td>${q.status}</td></tr>`).join("")||"<tr><td colspan=5>No payments.</td></tr>";}catch(e){alert(e.message)}});
function goBack(){location.href="schemes.html";}
function editScheme(){const id=new URLSearchParams(location.search).get("id");location.href=`schemes.html?editSchemeId=${encodeURIComponent(id)}`;}
function switchTab(name){document.querySelectorAll(".tab-content").forEach(x=>x.classList.remove("active"));const el=document.getElementById(name+"Tab");if(el)el.classList.add("active");}
function closeSidebar(){document.getElementById("sidebar")?.classList.remove("active");}
function toggleSidebar(){document.getElementById("sidebar")?.classList.toggle("active");}
async function addMember(){const id=new URLSearchParams(location.search).get("id");const m=await fintrackApi("/members");const available=m.members||[];const name=prompt("Enter exact member name:\n"+available.map(x=>`${x.id} — ${x.name}`).join("\n"));const member=available.find(x=>x.name.toLowerCase()===String(name||"").toLowerCase()||x.id===name);if(!member)return;const ticket=prompt("Ticket number:");if(!ticket)return;try{await fintrackApi(`/members/${member.id}/tickets`,{method:"POST",body:JSON.stringify({schemeId:id,ticketNumber:ticket})});location.reload();}catch(e){alert(e.message)}}
async function deleteMemberFromScheme(){const id=new URLSearchParams(location.search).get("id");const ticket=prompt("Enter ticket number to remove:");if(!ticket)return;alert("Tickets with payment history are protected. Remove is not available from this screen; contact database/admin workflow.");}
async function updateMonthlyWinner(){const id=new URLSearchParams(location.search).get("id");const month=Number(prompt("Winner month:"));const ticket=prompt("Winner ticket number:");if(!month||!ticket)return;try{await fintrackApi("/winners",{method:"POST",body:JSON.stringify({schemeId:id,month,ticketNumber:ticket})});location.reload();}catch(e){alert(e.message)}}
async function removeWinnerFromToolbar(){const id=new URLSearchParams(location.search).get("id");const d=await fintrackApi("/winners");const ws=(d.winners||[]).filter(x=>String(x.scheme?._id||x.scheme)===String(id));const ticket=prompt("Enter winning ticket number to remove:");const w=ws.find(x=>String(x.ticketNumber)===String(ticket));if(!w)return alert("Winner not found.");if(confirm("Remove this winner?")){await fintrackApi("/winners/"+w._id,{method:"DELETE"});location.reload();}}
async function stopWinnerMonth(){const id=new URLSearchParams(location.search).get("id");const month=Number(prompt("Month to mark stopped:"));if(!month)return;try{await fintrackApi("/winners/stopped",{method:"POST",body:JSON.stringify({schemeId:id,month})});location.reload();}catch(e){alert(e.message)}}
async function modifyStoppedMonth(){alert("Modify a stopped month by adding a winner from the Winners tab. The API prevents duplicate winner records.");}
async function addPayment(){const id=new URLSearchParams(location.search).get("id");const ticket=prompt("Ticket number:");const month=Number(prompt("Installment month:"));if(!ticket||!month)return;const m=await fintrackApi(`/schemes/${id}/tickets`);const t=(m.tickets||[]).find(x=>String(x.ticketNumber)===String(ticket));if(!t)return alert("Ticket not found");try{await fintrackApi("/payments/manual",{method:"POST",body:JSON.stringify({memberId:t.member._id,schemeId:id,ticketNumber:ticket,month,method:"Manual",transactionId:""})});location.reload();}catch(e){alert(e.message)}}
async function saveGoldMonthlyInstallments(){const id=new URLSearchParams(location.search).get("id");const d=await fintrackApi("/schemes/"+id),s=d.scheme;if(s.type!=="gold")return;const map={...(s.goldMonthlyInstallments||{})};for(let m=1;m<=Number(s.duration||0);m++){const v=prompt(`Gold monthly installment for Month ${m}:`,map[String(m)]||s.baseAmount||"");if(v===null)return;map[String(m)]=Number(v)||0;}try{await fintrackApi("/schemes/"+id,{method:"PATCH",body:JSON.stringify({goldMonthlyInstallments:map})});location.reload();}catch(e){alert(e.message)}}
function filterMembers(){location.reload()} function filterPayments(){location.reload()} function filterSchemes(){location.reload()} function refreshPayments(){location.reload()} function refreshSchemes(){location.reload()}
