let schemes=[];
function esc(v){return escHtml(v)}
async function loadSchemes(){try{schemes=(await fintrackApi("/schemes")).schemes.map(s=>({...s,id:s.id||s._id,type:s.chitType||s.type}));renderSchemes();}catch(e){console.error(e);alert(e.message)}}
function renderSchemes(){
 const body=document.getElementById("schemeTableBody"),search=(document.getElementById("schemeSearch")?.value||"").toLowerCase(),status=document.getElementById("statusFilter")?.value||"all";
 const rows=schemes.filter(s=>(status==="all"||s.status===status)&&(!search||[s.name,s.type,s.status].join(" ").toLowerCase().includes(search)));
 if(document.getElementById("totalSchemeCount"))document.getElementById("totalSchemeCount").textContent=schemes.length;
 if(document.getElementById("schemeResultCount"))document.getElementById("schemeResultCount").textContent=rows.length;
 if(body)body.innerHTML=rows.map(s=>`<tr><td><b>${esc(s.name)}</b><small>${esc(s.type)}</small></td><td>${s.type==="gold"?`${s.goldGrams||0} grams`:money(s.totalAmount)}</td><td>${money(s.baseAmount)}</td><td>${s.duration}</td><td>${s.capacity}</td><td>${dateText(s.startDate)}</td><td><span class="status ${s.status}">${esc(s.status)}</span></td><td><button class="btn btn-small" onclick="openEditSchemeModal('${s.id}')">Edit</button> <a class="btn btn-small" href="scheme-details.html?id=${encodeURIComponent(s.id)}">Details</a> <button class="btn btn-small danger" onclick="deleteScheme('${s.id}')">Delete</button></td></tr>`).join("")||`<tr><td colspan="9">No schemes found.</td></tr>`;
}
function openCreateSchemeModal(){document.getElementById("schemeForm")?.reset();document.getElementById("editSchemeId").value="";document.getElementById("schemeModalTitle").textContent="Create Scheme";document.getElementById("schemeStatus").value="upcoming";toggleSchemeFields();document.getElementById("schemeModal").classList.add("active");}
function openEditSchemeModal(id){const s=schemes.find(x=>String(x.id)===String(id));if(!s)return;openCreateSchemeModal();document.getElementById("schemeModalTitle").textContent="Edit Scheme";document.getElementById("editSchemeId").value=s.id;schemeName.value=s.name;schemeType.value=s.type;schemeAmount.value=s.totalAmount||"";schemeBaseAmount.value=s.baseAmount||"";schemeDuration.value=s.duration;schemeCapacity.value=s.capacity;schemeStartDate.value=String(s.startDate).slice(0,10);schemeStatus.value=s.status;toggleSchemeFields();}
function closeSchemeModal(){document.getElementById("schemeModal")?.classList.remove("active")}
function toggleSchemeFields(){const gold=schemeType?.value==="gold";if(totalAmountGroup)totalAmountGroup.style.display=gold?"none":"";schemeAmount.disabled=gold;schemeAmount.required=!gold;schemeBaseAmount.readOnly=!gold;schemeBaseAmount.required=gold;if(!gold&&schemeAmount.value)schemeBaseAmount.value=Math.round(Number(schemeAmount.value)*.05);}
async function saveScheme(e){e.preventDefault();const id=editSchemeId.value;const type=schemeType.value;const total=type==="gold"?0:Number(schemeAmount.value);const base=type==="gold"?Number(schemeBaseAmount.value):Math.round(total*.05);if(!schemeName.value.trim()||!schemeDuration.value||!schemeCapacity.value)return alert("Please fill all required fields.");if(type==="cash"&&total<=0)return alert("Enter total amount.");if(type==="gold"&&base<=0)return alert("Enter monthly gold-chit installment.");
 const payload={name:schemeName.value.trim(),chitType:type,totalAmount:total,baseAmount:base,goldGrams:type==="gold"?((schemeName.value.match(/(\d+(?:\.\d+)?)\s*(?:grams?|g)\b/i)||[])[1]||0):0,duration:Number(schemeDuration.value),capacity:Number(schemeCapacity.value),startDate:schemeStartDate.value,status:schemeStatus.value};
 try{if(id)await fintrackApi("/schemes/"+id,{method:"PATCH",body:JSON.stringify(payload)});else await fintrackApi("/schemes",{method:"POST",body:JSON.stringify(payload)});closeSchemeModal();await loadSchemes();}catch(err){alert(err.message)}}
async function deleteScheme(id){if(!confirm("Delete this scheme?"))return;try{await fintrackApi("/schemes/"+id,{method:"DELETE"});await loadSchemes();}catch(e){alert(e.message)}}
document.addEventListener("DOMContentLoaded",()=>{loadSchemes();schemeForm?.addEventListener("submit",saveScheme);schemeType?.addEventListener("change",toggleSchemeFields);schemeAmount?.addEventListener("input",toggleSchemeFields);schemeSearch?.addEventListener("input",renderSchemes);statusFilter?.addEventListener("change",renderSchemes);toggleSchemeFields();});

function filterSchemes(){renderSchemes()} function refreshSchemes(){loadSchemes()} function editScheme(id){openEditSchemeModal(id)}
